import type { ThemeConfig } from 'antd'
import { designTokens } from './designTokensDark'

export const antdDarkTheme: ThemeConfig = {
  token: {
    colorBgContainer: designTokens.colorSurface,
    colorBgElevated: designTokens.colorSurface,
    colorBorder: designTokens.colorBorder,
    colorBorderSecondary: designTokens.colorBorder,
    colorText: designTokens.colorText2,
    colorTextSecondary: designTokens.colorText2,
    colorTextQuaternary: designTokens.colorText3,
    colorTextPlaceholder: designTokens.colorText3,
    colorTextHeading: designTokens.colorText1,
    colorIcon: designTokens.colorText3,
    colorIconHover: designTokens.colorText1,
    colorFillAlter: designTokens.colorHoverFill,
    controlItemBgHover: designTokens.colorRowHover,
  },
  components: {
    Input: {
      activeBg: designTokens.colorSurface,
      hoverBg: designTokens.colorHoverFill,
      addonBg: designTokens.colorSurface,
      hoverBorderColor: designTokens.colorBorderHover,
      activeBorderColor: designTokens.colorBorderHover,
      activeShadow: `0 0 0 2px ${designTokens.colorFocusRing}`,
    },
    Select: {
      selectorBg: designTokens.colorSurface,
      clearBg: designTokens.colorSurface,
      hoverBorderColor: designTokens.colorBorderHover,
      activeBorderColor: designTokens.colorBorderHover,
      activeOutlineColor: designTokens.colorFocusRing,
      optionActiveBg: designTokens.colorHoverFill,
      optionSelectedBg: designTokens.colorAccent,
      optionSelectedColor: designTokens.colorText1,
    },
    DatePicker: {
      hoverBg: designTokens.colorHoverFill,
      activeBg: designTokens.colorSurface,
      hoverBorderColor: designTokens.colorBorderHover,
      activeBorderColor: designTokens.colorBorderHover,
      activeShadow: `0 0 0 2px ${designTokens.colorFocusRing}`,
      cellHoverBg: designTokens.colorHoverFill,
      cellActiveWithRangeBg: designTokens.colorAccent,
      cellHoverWithRangeBg: designTokens.colorHoverFill,
      cellRangeBorderColor: designTokens.colorBorderHover,
    },
    InputNumber: {
      hoverBg: designTokens.colorHoverFill,
      activeBg: designTokens.colorSurface,
      hoverBorderColor: designTokens.colorBorderHover,
      activeBorderColor: designTokens.colorBorderHover,
      activeShadow: `0 0 0 2px ${designTokens.colorFocusRing}`,
      handleBg: designTokens.colorSurface,
      handleActiveBg: designTokens.colorHoverFill,
      handleBorderColor: designTokens.colorBorder,
      handleHoverColor: designTokens.colorText1,
    },
    Button: {
      defaultBg: designTokens.colorSurface,
      defaultBorderColor: designTokens.colorBorder,
      defaultColor: designTokens.colorText2,
      defaultHoverBg: designTokens.colorHoverFill,
      defaultHoverBorderColor: designTokens.colorBorderHover,
      defaultHoverColor: designTokens.colorText1,
      defaultActiveBg: designTokens.colorSurface,
      defaultActiveBorderColor: designTokens.colorBorderHover,
      defaultActiveColor: designTokens.colorText1,
    },
    Pagination: {
      itemBg: designTokens.colorSurface,
      itemLinkBg: designTokens.colorSurface,
      itemInputBg: designTokens.colorSurface,
      itemActiveBg: designTokens.colorAccent,
      itemActiveColor: designTokens.colorText1,
      itemActiveColorHover: designTokens.colorText1,
    },
    Table: {
      headerBg: 'transparent',
      headerColor: designTokens.colorText3,
      headerSortActiveBg: designTokens.colorHoverFill,
      headerSortHoverBg: designTokens.colorHoverFill,
      bodySortBg: 'transparent',
      rowHoverBg: designTokens.colorRowHover,
      borderColor: designTokens.colorTableBorder,
      headerSplitColor: 'transparent',
      footerBg: 'transparent',
      footerColor: designTokens.colorText2,
    },
    Card: {
      headerBg: 'transparent',
      actionsBg: 'transparent',
      extraColor: designTokens.colorText2,
    },
  },
}
